name: Terraform Plan & Security Scan (Lab 2)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform + Checkov Pipeline
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      # -----------------------
      # Checkout source code
      # -----------------------
      - name: Checkout source
        uses: actions/checkout@v4

      # -----------------------
      # Setup Python (for Checkov)
      # -----------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # -----------------------
      # Install Checkov
      # -----------------------
      - name: Install Checkov
        run: |
          pip install checkov==3.2

      # -----------------------
      # Run Checkov Security Scan
      # -----------------------
      - name: Run Checkov scan
        run: |
          checkov -d ./terraform \
            --skip-check CKV_AWS_79,CKV_AWS_126,CKV_AWS_135,CKV_AWS_8,CKV_AWS_23,CKV_AWS_130,CKV2_AWS_5,CKV2_AWS_12,CKV2_AWS_11,CKV2_AWS_41,CKV2_AWS_19,CKV_AWS_24 \
            --compact \
            --quiet

      # -----------------------
      # Setup Terraform
      # -----------------------
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      # -----------------------
      # Terraform Init
      # -----------------------
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # -----------------------
      # Terraform Plan
      # -----------------------
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      # -----------------------
      # Terraform Apply (only on push)
      # -----------------------
      - name:  Terraform Apply
        if: github. event_name == 'push'
        run: terraform apply -auto-approve
        working-directory:  ./terraform